project:
  name: connect-integration-dialogtech
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - us-east-1
tests:
  defaults:
    parameters: {}
    regions:
    - us-east-1
    template: templates/dialogtech.template.yaml
